In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/matin/Desktop/Codes/Projects/MarketPulse/data/oxostreetwear_20260808_161908.csv')
df.head()

,post_index,description,price,engagement,comments,views,reactions,posted_at,post_url
0,1,ترکیب رنگ جدید سری نارنجی 🍊\n‌\nاورنج لیبل سری...,8000000.0,2116,NaN,2116,0,2026-04-14T10:40:51.145000+00:00,https://ble.ir/oxostreetwear
1,2,⁨ ‌جردن ساق کوتاه مشکی کرم با جزئیات سبز و زیر...,9750000.0,3912,NaN,3912,0,2026-04-14T10:41:55.625000+00:00,https://ble.ir/oxostreetwear
2,3,ایرمکس پلاس (TN) سفید با جزئیات سبز\n\nتکنولوژ...,6500000.0,5011,NaN,5011,0,2026-04-14T10:42:50.182000+00:00,https://ble.ir/oxostreetwear
3,4,اسنیکری که با الهام گرفتن از دوربین‌های دستی و...,8000000.0,7045,NaN,7045,0,2026-04-14T10:43:35.963000+00:00,https://ble.ir/oxostreetwear
4,5,ایرفورس سوپریم [کانسپت]\nمتریال چرم با جزئیات ...,8000000.0,8013,NaN,8013,0,2026-04-14T10:44:16.760000+00:00,https://ble.ir/oxostreetwear

In [6]:
reversed_df = df.iloc[::-1]
reversed_df = reversed_df.reset_index(drop=True)
reversed_df.head(10)

,post_index,description,price,engagement,comments,views,reactions,posted_at,post_url
0,70,ایرفورس‌های متفاوت رو از دست نده، از هر کدوم ی...,10000000.0,1527,NaN,1527,0,2026-06-16T14:22:58.089000+00:00,https://ble.ir/oxostreetwear
1,69,ایرجردن ساقدار کمیاب!\nبا متریال ساتن و جزئیات...,13000000.0,2222,NaN,2222,0,2026-06-10T08:32:47.935000+00:00,https://ble.ir/oxostreetwear
2,68,دانک طوسی با متریال جیر\n\nقابلیت خرید ۴ قسطه ...,10000000.0,2469,NaN,2469,0,2026-06-07T13:37:38.032000+00:00,https://ble.ir/oxostreetwear
3,67,VANS 🔥\nپرطرفدارترین سری ونس، Knu Skool\nبا طر...,10000000.0,3239,NaN,3239,0,2026-06-02T09:42:51.289000+00:00,https://ble.ir/oxostreetwear
4,66,روز اخر تخفیف رو از دست نده!\n\nبا اسنپ‌پی ۴ ق...,NaN,3412,NaN,3412,0,2026-05-31T12:20:08.468000+00:00,https://ble.ir/oxostreetwear
5,65,کمتر از *12 ساعت* تا پایان تخفیف اسنپ‌پی\nاین ...,NaN,3094,NaN,3094,0,2026-05-31T09:34:44.167000+00:00,https://ble.ir/oxostreetwear
6,64,ساق بلند‌های فروشگاه رو از دست نده!\n\nبا اسنپ...,NaN,3347,NaN,3347,0,2026-05-30T12:36:36.321000+00:00,https://ble.ir/oxostreetwear
7,63,سعی کنید از آخرین روز‌های جشنواره‌ی اسنپ‌پی اس...,500000.0,3108,NaN,3108,0,2026-05-30T09:38:32.286000+00:00,https://ble.ir/oxostreetwear
8,62,خوبای اسنپ‌پی تخفیفشون بیشتر شده 🔥\n\nکد تخفیف...,300000.0,3621,NaN,3621,0,2026-05-29T11:11:36.640000+00:00,https://ble.ir/oxostreetwear
9,61,سری فیلد نایکی جزو کفش‌های کژوال روزمره حساب م...,7000000.0,4532,NaN,4532,0,2026-05-26T13:36:42.980000+00:00,https://ble.ir/oxostreetwear

In [4]:
avg_price = df['price'].mean()
print(f"The average price is: {avg_price:.2f}")
avg_price_reversed = reversed_df['price'].mean()
print(f"The average price of reversed dataframe is: {avg_price:.2f}")

The average price is: 7445745.11
The average price of reversed dataframe is: 7445745.11

In [7]:
cheaper_rows_df = reversed_df[reversed_df['price'] < 200000]
display(cheaper_rows_df.head())

,post_index,description,price,engagement,comments,views,reactions,posted_at,post_url
15,55,فروش رفت!\n\nاز تک سایز‌ها یک جفت موجوده، پیشن...,150000.0,4927,NaN,4927,0,2026-05-24T11:36:36.544000+00:00,https://ble.ir/oxostreetwear
17,53,مدل‌های تک سایز رو با کد تخفیف اسنپ‌پی سفارش ب...,150000.0,5324,NaN,5324,0,2026-05-23T14:54:42.001000+00:00,https://ble.ir/oxostreetwear
44,26,تا قبل از ۱۲ شب مهلت دارید با قیمت قبلی ثبت سف...,20.0,12118,NaN,12118,0,2026-05-01T16:45:41.094000+00:00,https://ble.ir/oxostreetwear